### ISSUE TITLE
Allow skipping patch version in CLI

### ISSUE THREAD

**Issue by jaskij** [foresterre/cargo-msrv#340] opened 2022-03-31 14:46 UTC
```shell
$ cargo msrv --bisect --min 1.54  
unexpected end of input while parsing minor version number
```
It would make a lot of sense to interpret that as either `1.54.0` or latest patch in `1.54`, instead of failing.

**Comment by foresterre** [comment] 2022-03-31 22:34
Absolutely 😅! Thanks for the request :)

Duplicate of https://github.com/foresterre/cargo-msrv/issues/278

**Closed** 2022-03-31 22:35 UTC
Labels: Z-duplicate

**Comment by jaskij** [comment] 2022-03-31 22:36
Ah, sorry for the duplicate.

**Comment by foresterre** [comment] 2022-03-31 22:44
No worries! :)
