### ISSUE TITLE
Fails on macOS

### ISSUE THREAD

**Issue by mainrs** [foresterre/cargo-msrv#63] opened 2021-04-06 00:31 UTC
I just tried the tool out and it doesn't work for me:

```console
project-rs on  main [?] is 📦 v0.1.0 via 🦀 v1.51.0 took 12s
❯ cargo msrv
Determining the Minimum Supported Rust Version (MSRV) for toolchain x86_64-apple-darwin
Using check command cargo build --all
   Done red light for 1.51.0      █░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 00:00:01
   Failed check command cargo build --all didn't succeed
Unable to find a Minimum Supported Rust Version (MSRV).

If you think this result is erroneous, please run: `cargo build --all` manually.

If the above does succeed, or you think cargo-msrv errored in another way, please feel free to
report the issue at: https://github.com/foresterre/cargo-msrv/issues

Thank you in advance!
```

Running `cargo check` works and the exit code is 0.

__rustc:__ rustc 1.51.0 (2fd73fabe 2021-03-23)
__macOS:__ Big Sur 11.2.3 (20D91)

**Comment by foresterre** [comment] 2021-04-07 06:30
Hi, thank you for taking the time to report this issue!

I've had a look, but am so far unable to reproduce it (it unfortunately doesn't help that I've no computer with macOS).

I've been running a few tests in a different repo on the github actions CI, but am not able to produce the same error.
I used the following source code: [lib.rs](https://github.com/foresterre/cargo-msrv-macos-testing/blob/main/src/lib.rs) which gates on Rust 1.48.0; and produces the following MSRV result on macOS:
https://github.com/foresterre/cargo-msrv-macos-testing/runs/2284768412?check_suite_focus=true#step:10:8 (`1.48.0`)


A few ways to further debug this are:
* I see you are using `cargo check` while the tool tried building with `cargo build --all`, could you run `cargo build --all` on your repo too?
* If you run `rustup toolchain list`, what output is produced? (^1)
* If you are willing to, you could install the latest development version with `cargo install cargo-msrv --git https://github.com/foresterre/cargo-msrv.git --branch main` and try it again
* If you are willing to, and your repo is public, you could share your repo so I can run the tool on that
* If you are willing, you could clone my [test]((https://github.com/foresterre/cargo-msrv-macos-testing/blob/main/src/lib.rs)) repo and try running `cargo msrv` on that; it should output 1.48.0 as MSRV
* I could add more logging (I removed logs earlier, but wanted to add them back anyhow; this will have to wait until late next week though)


^1 sample output of `rustup toolchain list` for current device:
```
stable-x86_64-unknown-linux-gnu (default)
nightly-2020-09-12-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu
1.34.0-x86_64-unknown-linux-gnu
1.35.0-x86_64-unknown-linux-gnu
1.36.0-x86_64-unknown-linux-gnu
1.37.0-x86_64-unknown-linux-gnu
1.38.0-x86_64-unknown-linux-gnu
1.39.0-x86_64-unknown-linux-gnu
1.40.0-x86_64-unknown-linux-gnu
1.41.0-x86_64-unknown-linux-gnu
1.41.1-x86_64-unknown-linux-gnu
1.42.0-x86_64-unknown-linux-gnu
1.43.0-x86_64-unknown-linux-gnu
1.43.1-x86_64-unknown-linux-gnu
1.44.0-x86_64-unknown-linux-gnu
1.44.1-x86_64-unknown-linux-gnu
1.45.0-x86_64-unknown-linux-gnu
1.45.1-x86_64-unknown-linux-gnu
1.45.2-x86_64-unknown-linux-gnu
1.46.0-x86_64-unknown-linux-gnu
1.47.0-x86_64-unknown-linux-gnu
1.48.0-x86_64-unknown-linux-gnu
1.49.0-x86_64-unknown-linux-gnu
1.50.0-x86_64-unknown-linux-gnu
1.51.0-x86_64-unknown-linux-gnu
```

**Comment by foresterre** [comment] 2021-09-24 00:00
I will close this issue as "can not reproduce". Feel free to re-open or open a new issue in case you think its not solved.

**Closed by foresterre** 2021-09-24 00:00 UTC
Labels: C-bug, S-cannot-reproduce-yet
